CREATE TABLE `PEOPLE` (
	`Id` INT(10) unsigned NULL DEFAULT NULL,
	`FirstName` VARCHAR(50) NULL DEFAULT NULL,
	`LastName` VARCHAR(50) NULL DEFAULT NULL,
	`Address` VARCHAR(50) NULL DEFAULT NULL,
	`Gender` VARCHAR(50) NULL DEFAULT null
)
ENGINE=InnoDB
;

ALTER TABLE PEOPLE CHANGE ID ID INT(10) AUTO_INCREMENT PRIMARY KEY;